export const customStyles = {
  control: (baseStyles, state) => ({
    ...baseStyles,
    borderWidth: "0px",
    padding: "0px",
    backgroundColor: "#fff",
    border: state.isFocused && "0px solid #ccc",
    boxShadow: state.isFocused ? "none" : "none",
    "&:hover": {
      borderWidth: "0px",
    },
  }),
  option: (styles, { data, isDisabled, isFocused, isSelected }) => ({
    ...styles,
    backgroundColor: isFocused ? "#3b424e" : isSelected ? "#3b424e" : "#fff",
    color: isFocused && "white",
    fontWeight: "400",
    ":active": {
      ...styles[":active"],
      backgroundColor: "#3b424e",
    },
  }),
  multiValueLabel: (styles, { data }) => ({
    ...styles,
    fontSize: "1rem",
    fontWeight: "400",
    color: "rgb(75 85 99)",
    backgroundColor: "rgb(243 244 246)",
  }),
  multiValueRemove: (styles, { data }) => ({
    ...styles,
    fontSize: "1rem",
    fontWeight: "700",
    color: "rgb(75 85 99)",
    backgroundColor: "rgb(243 244 246)",
    "&:hover": {
      backgroundColor: "rgb(243 244 246)",
    },
  }),
};

export const options = [
  { value: "tecnología", label: "Tecnología" },
  { value: "programación", label: "Programación" },
  { value: "desarrollo-web", label: "Desarrollo web" },
  { value: "desarrollo-móvil", label: "Desarrollo móvil" },
  { value: "diseño", label: "Diseño" },
  { value: "marketing-digital", label: "Marketing digital" },
  { value: "redes-sociales", label: "Redes sociales" },
  { value: "emprendimiento", label: "Emprendimiento" },
  { value: "productividad", label: "Productividad" },
  { value: "gestión-de-proyectos", label: "Gestión de proyectos" },
  { value: "negocios", label: "Negocios" },
  { value: "finanzas", label: "Finanzas" },
  { value: "economía", label: "Economía" },
  { value: "startups", label: "Startups" },
  { value: "innovación", label: "Innovación" },
  { value: "inteligencia-artificial", label: "Inteligencia artificial" },
  { value: "big-data", label: "Big data" },
  { value: "ciberseguridad", label: "Ciberseguridad" },
  { value: "cloud-computing", label: "Cloud computing" },
  { value: "internet-de-las-cosas", label: "Internet de las cosas" },
  { value: "blockchain", label: "Blockchain" },
  { value: "criptomonedas", label: "Criptomonedas" },
  { value: "ciencia", label: "Ciencia" },
  { value: "medicina", label: "Medicina" },
  { value: "salud", label: "Salud" },
  { value: "psicología", label: "Psicología" },
  { value: "filosofía", label: "Filosofía" },
  { value: "arte", label: "Arte" },
  { value: "literatura", label: "Literatura" },
  { value: "historia", label: "Historia" },
  { value: "cultura", label: "Cultura" },
  { value: "deporte", label: "Deporte" },
  { value: "viajes", label: "Viajes" },
  { value: "gastronomía", label: "Gastronomía" },
  { value: "moda", label: "Moda" },
  { value: "belleza", label: "Belleza" },
  { value: "decoración", label: "Decoración" },
  { value: "jardinería", label: "Jardinería" },
  { value: "animales", label: "Animales" },
  { value: "medio-ambiente", label: "Medio ambiente" },
  { value: "derecho", label: "Derecho" },
  { value: "política", label: "Política" },
  { value: "relaciones-internacionales", label: "Relaciones internacionales" },
  { value: "psicología-social", label: "Psicología social" },
  { value: "educación", label: "Educación" },
  { value: "idiomas", label: "Idiomas" },
  { value: "viajes-espaciales", label: "Viajes espaciales" },
  { value: "ciencia-ficción", label: "Ciencia ficción" },
  { value: "fantasía", label: "Fantasía" },
  { value: "terror", label: "Terror" },
  { value: "comedia", label: "Comedia" },
];
